---
- name: Install Communication software from the internet
  apt:
    deb: "{{ item }}"
  loop:
    - "{{ slack_deb_url }}"
    - "{{ discord_deb_url }}"
    - "{{ keybase_deb_url }}"
    - "{{ mattermost_deb_url }}"

- name: Install Communication software from repos
  apt:
    name: "{{ irc_client }}"
    state: latest
    update_cache: true
    install_recommends: true
