---
- name: Install Communication software for yum hosts
  yum:
    name:
      - "{{ slack_rpm_url }}"
      - "{{ keybase_rpm_url }}"
      - "{{ irc_client }}"
    state: present

- name: Ensure directories exist in opt to install too
  file:
    path:
      - '/opt/mattermost'
      - '/opt/discord'
    state: directory
    owner: root
    group: root

- name: Install software from the internet
  unarchive:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: true
  loop:
    - {src: "{{ discord_tar_url }}", dest: /opt/discord}
    - {src: "{{ mattermost_tar_url }}", dest: /opt/mattermost}

- name: Ensure software is linked in path
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - {src: /opt/discord/discord, dest: /usr/bin/discord}
    - {src: /opt/mattermost/bin/mattermost-desktop, dest: /usr/bin/mattermost-desktop}
