---
all:
  vars:
    local_dns:
      - 192.168.66.11
      - 1.1.1.1                       # Cloudflare
      - 1.0.0.1                       # Cloudflare
      #- 2606:4700:4700::1111         # Cloudflare
      #- 2606:4700:4700::1001         # Cloudflare
      #- 84.200.69.80                 # DNSWatch
      #- 84.200.70.40                 # DNSWatch
      #- 9.9.9.9                      # Quad9
      #- 149.112.112.112              # Quad9

    desktop_mgr:                      # Only use one at a time
      #- 'none'
      - 'lightdm'
      #- 'sddm'
      #- 'gdm'
    desktop_env:                      # can select multiple
      #- 'none'
      - 'xfce'
      #- 'i3'
      #- 'gnome'
      #- 'budgie'
      #- 'kde'
      #- 'mate'

    sound_enabled: true

    text_editor:
      #- 'atom'
      #- 'sublime'

    ide:
      #- 'intellij'
      #- 'vscode'

    terminal:
      #- 'rxvt'
      #- 'terminator'
      #- 'kitty'

  children:
    linux:
      hosts:
        ubuntu:
          ansible_host: 192.168.66.50
          ansible_python_interpreter: '/usr/bin/python3'
          admin_user: 'sean'
          cpu: 'None'
        centos:
          ansible_host: 192.168.66.51
          ansible_python_interpreter: '/usr/bin/python3'
          admin_user: 'sean'
          desktop_env:
            - 'none'
            #- 'xfce'
            #- 'gnome'
            #- 'kde'
            #- 'mate'
        arch:
          ansible_host: 192.168.66.52
          ansible_python_interpreter: '/usr/bin/python3'
          admin_user: 'sean'
          cpu: 'none'
        debian:
          ansible_host: 192.168.66.53
          ansible_python_interpreter: '/usr/bin/python3'
          admin_user: 'sean'
          cpu: 'None'
#        kali:
#          ansible_host: 192.168.66.54
#    windows:
#      hosts:
#        windows10:
#          ansible_host: 192.168.66.55
