---
all:
  children:
    linux:
      hosts:
        ubuntu:
          ansible_host: 192.168.66.50
          ansible_python_interpreter: '/usr/bin/python3'
          admin_user: 'sean'
          desktop_env:
            - 'xfce'
            - 'i3'
        centos:
          ansible_host: 192.168.66.51
          ansible_python_interpreter: '/usr/bin/python3'
          admin_user: 'sean'
          desktop_env:
            - 'xfce'
        arch:
          ansible_host: 192.168.66.52
          ansible_python_interpreter: '/usr/bin/python3'
          admin_user: 'sean'
          desktop_env:
            - 'xfce'
            - 'i3'
        debian:
          ansible_host: 192.168.66.53
          ansible_python_interpreter: '/usr/bin/python3'
          admin_user: 'sean'
          desktop_env:
            - 'xfce'
            - 'i3'
#        kali:
#          ansible_host: 192.168.66.54
#    windows:
#      windows10:
#        ansible_host: 192.168.66.55
