---
- hosts: all
  gather_facts: true
  tasks:
    - name: Test connection
      ping:
  roles:
    - {role: arc.ansible_config, become: true}
    - {role: arc.user_creation, become: true}
    - {role: arc.remove_users, become: true}
    - {role: arc.git, become: true}
    - {role: arc.vim, become: true}
    - {role: arc.bash_it, become: true}