---
# Tasks to be performed on Arch systems
- name: Install base packages for Debian Linux
  apt:
    name: "{{ debian_packages }}"
    state: latest
    update_cache: true
    install_recommends: true

- name: Install microcode for AMD CPUs
  apt:
    name:
      - 'amd64-microcode'
      - 'linux-headers-amd64'
    state: latest
    update_cache: true
    install_recommends: true
  when: cpu == 'AMD'

- name: Install microcode for Intel CPUs
  apt:
    name:
      - 'intel-microcode'
      - 'linux-headers-amd64'
    state: latest
    update_cache: true
    install_recommends: true
  when: cpu == 'Intel'

- name: Install microcode for Raspberry Pi
  apt:
    name:
      - 'raspberrypi-kernel-headers'
    state: latest
    update_cache: true
    install_recommends: true
  when: cpu == 'RaspPi'
