---
# Tasks to be performed on Arch systems
- name: Install base packages for Debian Linux
  apt:
    name: "{{ debian_packages }}"
    state: latest
    update_cache: true
    install_recommends: true
