---
# tasks file for arc.baseline_pkgs
- name: Install base packages for Arch
  import_tasks: arch.yml
  when: ansible_distribution == 'Archlinux'

- name: Install base packages for CentOS
  import_tasks: centos.yml
  when: ansible_distribution == 'CentOS'

- name: Install base packages for Debian
  import_tasks: debian.yml
  when: ansible_distribution == 'Debian'

- name: Install base packages for Ubuntu
  import_tasks: ubuntu.yml
  when: ansible_distribution == 'Ubuntu'
