---
# Task files for arc.desktop_env.budgie
# I also couldn't find a way to install Budgie in yum/dnf systems currently
# This is something I'll have to come back too; there was an old repo for it
# in earlier versions of CentOS/RHEL, but it doesn't seem like it's supported
# any more
- name: Install budgie on Ubuntu hosts
  apt:
    name: ubuntu-budgie-desktop
    state: present
    update_cache: true
    install_recommends: true
  when: ansible_pkg_mgr == 'apt' and
        ansible_distribution == 'Ubuntu'

- name: Install budgie on apt hosts
  apt:
    name:
      - budgie-desktop
      - budgie-indicator-applet
    state: latest
    update_cache: true
    install_recommends: true
  when: ansible_pkg_mgr == 'apt' and
        ansible_distribution != 'Ubuntu'

- name: Install budgie on pacman systems
  pacman:
    name:
      - budgie-desktop
    state: latest
    update_cache: true
  when: ansible_pkg_mgr == 'pacman'
