---
# Run tasks to install a DM on all systems
- name: Install DM on Ubuntu hosts
  apt:
    name: "{{ desktop_mgr }}"
    state: latest
    update_cache: true
    install_recommends: true
  when: ansible_pkg_mgr == 'apt'

- name: Install DM on yum systems
  yum:
    name: "{{ desktop_mgr }}"
    state: latest
    update_cache: true
  when: ansible_pkg_mgr == 'yum'

- name: Install DM on dnf systems
  dnf:
    name: "{{ desktop_mgr }}"
    state: latest
    update_cache: true
  when:
    - ansible_pkg_mgr == 'dnf'
    - desktop_mgr == 'lightdm'
  register: dnf_system

- name: Install DM on pacman systems
  pacman:
    name: "{{ desktop_mgr }}"
    state: latest
    update_cache: true
  when: ansible_pkg_mgr == 'pacman'

- name: Ensure greeter is installed on pacman systems if lightdm
  pacman:
    name: 'lightdm-deepin-greeter'
    state: latest
    update_cache: true
  when:
    - ansible_pkg_mgr == 'pacman'
    - desktop_mgr == 'lightdm'

- name: Ensure DM service is enabled
  service:
    name: "{{ desktop_mgr[0] }}"
    state: started
    enabled: true

- name: Install DM on dnf systems if lightdm is selected
  dnf:
    name: 'gdm'
    state: latest
    update_cache: true
  when:
    - ansible_pkg_mgr == 'dnf'
    - dnf_system.skipped

- name: Ensure service is started if lightdm is selected for dnf system
  service:
    name: 'gdm'
    state: started
    enabled: true
  when:
     - ansible_pkg_mgr == 'dnf'
     - dnf_system.skipped
