---
# Task files for arc.desktop_env.i3
# Note: there is no install for DNF here because i3 is not supported
# in the latest CentOS or EPEL repos for some ungodly reason.  That was
# such a waste of time...
- name: Install i3 on apt hosts
  apt:
    name:
      - lxappearance
      - thunar
      - arc-theme
      - moka-icon-theme
      - i3blocks
      - i3
      - xorg
      - suckless-tools
    state: latest
    update_cache: true
    install_recommends: true
  when: ansible_pkg_mgr == 'apt'

- name: Install i3 on yum systems
  yum:
    name:
     - lxappearance
     - thunar
     - arc-theme
     - moka-icon-theme
     - i3blocks
     - i3
     - xorg
     - suckless-tools
    state: latest
    update_cache: true
  when: ansible_pkg_mgr == 'yum'

- name: Install i3 on pacman systems
  pacman:
    name:
      - lxappearance
      - thunar
      - moka-icon-theme
      - i3blocks
      - i3-gaps
      - i3lock
      - i3status
      - xorg
    state: latest
    update_cache: true
  when: ansible_pkg_mgr == 'pacman'

- name: Copy i3 config files
  copy:
    src: "{{ item.sr }}"
    dest: "{{ item.dest }}"
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
  loop:
    - {src: i3, dest: /home/"{{ admin_usr }}"/.config/i3}
    - {src: wallpapers, dest: /home/"{{ admin_usr }}"/.config/i3/wallpapers}
