---
# Task files for arc.desktop_env.kde
# I removed KDE from yum because I have no way to test
# without working on a system that use DNF
- name: Install kde on Ubuntu hosts
  apt:
    # kde-full: includes all the things for KDE
    # kde-standard: includes the standard KDE apps
    # kde-plasma-desktop: just KDE
    name: kde-standard
    state: latest
    update_cache: true
    install_recommends: true
  when: ansible_pkg_mgr == 'apt' and
        ansible_distribution != 'Debian'

- name: Install kde on Debian hosts
  apt:
    name: task-kde-desktop
    state: latest
    update_cache: true
    install_recommends: true
  when: ansible_pkg_mgr == 'apt' and
        ansible_distribution == 'Debian'

# TODO: Fix installing KDE on dnf systems
#- name: Install kde on dnf systems
#  dnf:
#    name: '@KDE Plasma Workspaces'
#    state: latest
#    update_cache: true
#  when: ansible_pkg_mgr == 'dnf'

- name: Install kde on pacman systems
  pacman:
    name:
      - plasma
    state: latest
    update_cache: true
  when: ansible_pkg_mgr == 'pacman'
