---
# tasks file for arc.desktop_env
- name: Ensure desktop manager is installed
  import_tasks: dm.yml

- name: Install Xfce
  import_tasks: xfce.yml
  when: "'xfce' in desktop_env"

- name: Install Gnome
  import_tasks: gnome.yml
  when: "'gnome' in desktop_env"

- name: Install KDE
  import_tasks: kde.yml
  when: 'kde' in "{{ desktop_env }}"

- name: Install i3
  import_tasks: i3.yml
  when: "'i3' in desktop_env"

- name: Install MATE
  import_tasks: mate.yml
  when: 'mate' in "{{ desktop_env }}"

- name: Install Budgie
  import_tasks: budgie.yml
  when: 'budgie' in "{{ desktop_env }}"

#- name: Remove unspecified desktop environments
#  import_tasks: remove_de.yml
