---
# Tasks for arc.desktop_env.remove_de
- name: Disable SDDM if not in use
  service:
    name: 'sddm'
    state: stopped
    enabled: false
  when:
    - "'sddm' not in desktop_mgr"
    - ansible_distribution != 'CentOS'
  ignore_errors: true

- name: Remove SDDM from systems when not in use
  package:
    name: 'sddm'
    state: 'absent'
  when:
    - "'sddm' not in desktop_mgr"
    - ansible_distribution != 'CentOS'
    - ansible_distribution != 'Archlinux'

# Arch just wants to be difficult...
- name: Remove SDDM from Arch systems
  pacman:
    name:
      - sddm
    state: absent
    extra_args: --recursive
    force: true
  when:
    - "'sddm' not in desktop_mgr"
    - ansible_distribution == 'Archlinux'

- name: Disable LightDM if not in use
  service:
    name: 'lightdm'
    state: stopped
    enabled: false
  when: "'lightdm' not in desktop_mgr"
  ignore_errors: true

- name: Remove LightDM from systems when not in use
  package:
    name: 'lightdm'
    state: 'absent'
  when:
    - "'lightdm' not in desktop_mgr"
    - ansible_distribution != 'Archlinux'

- name: Remove LightDM from Arch systems
  pacman:
    name:
      - lightdm
      - lightdm-deepin-greeter
    state: absent
    extra_args: --recursive
    force: true
  when:
    - "'lightdm' not in desktop_mgr"
    - ansible_distribution == 'Archlinux'

- name: Disable GDM if not in use
  service:
    name: 'gdm'
    state: stopped
    enabled: false
  when: "'gdm' not in desktop_mgr"
  ignore_errors: true

- name: Remove GDM from systems when not in use
  package:
    name: 'gdm'
    state: 'absent'
  when: "'gdm' not in desktop_mgr"

- name: Remove Budgie if not in use on ubuntu systems
  apt:
    name: ubuntu-budgie-desktop
    state: absent
    autoremove: true
  when:
    - ansible_distribution == 'Ubuntu'
    - "'budgie' not in desktop_env"

- name: Remove budgie if not in use on apt systems
  apt:
    name:
      - budgie-desktop
      - budgie-indicator-applet
    state: absent
    autoremove: true
  when:
    - ansible_pkg_mgr == 'apt'
    - ansible_distribution != 'Ubuntu'
    - "'budgie' not in desktop_env"

- name: Remove budgie if not in use on pacman systems
  pacman:
    name: budgie-desktop
    state: absent
  when:
    - ansible_pkg_mgr == 'pacman'
    - "'budgie' not in desktop_env"

- name: Remove Gnome if not in use on apt systems
  apt:
    name: gnome
    state: absent
    autoremove: true
  when:
    - ansible_pkg_mgr == 'apt'
    - ansible_distribution != 'Debian'
    - "'gnome' not in desktop_env"

- name: Remove Gnome if not in use on Debian systems
  apt:
    name: task-gnome-desktop
    state: absent
    autoremove: true
  when:
    - ansible_pkg_mgr == 'apt'
    - ansible_distribution == 'Debian'
    - "'gnome' not in desktop_env"

- name: Remove Gnome if not in use on dnf systems
  dnf:
    name: '@GNOME'
    state: absent
    autoremove: true
  when:
    - ansible_pkg_mgr == 'dnf'
    - "'gnome' not in desktop_env"

- name: Remove Gnome if not in use on pacman systems
  pacman:
    name:
      - gnome
      - gnome-extra
    state: absent
  when:
    - ansible_pkg_mgr == 'pacman'
    - "'gnome' not in desktop_env"

- name: Remove i3 if not in use on apt hosts
  apt:
    name:
      - lxappearance
      - i3blocks
      - i3
      - suckless-tools
    state: absent
    autoremove: true
  when:
    - ansible_pkg_mgr == 'apt'
    - "'i3' not in desktop_env"

- name: Remove i3 if not in use on yum hosts
  yum:
    name:
     - lxappearance
     - i3blocks
     - i3
     - suckless-tools
    state: absent
    autoremove: true
  when:
    - ansible_pkg_mgr == 'yum'
    - "'i3' not in desktop_env"

- name: Remove i3 if not in use on pacman systems
  pacman:
    name:
      - lxappearance
      - i3blocks
      - i3-gaps
      - i3lock
      - i3status
    state: absent
  when:
    - ansible_pkg_mgr == 'pacman'
    - "'i3' not in desktop_env"

- name: Remove KDE if not in use on apt hosts
  apt:
    name:
      - kde-full
      - kde-standard
      - kde-plasma-desktop
    state: absent
    autoremove: true
  when:
    - ansible_pkg_mgr == 'apt'
    - ansible_distribution != 'Debian'
    - "'kde' not in desktop_env"

- name: Remove KDE if not in use on Debian hosts
  apt:
    name: task-kde-desktop
    state: absent
    autoremove: true
  when:
    - ansible_pkg_mgr == 'apt'
    - ansible_distribution == 'Debian'
    - "'kde' not in desktop_env"

- name: Remove KDE if not in use on dnf hosts
  dnf:
    name: '@KDE Plasma Workspaces'
    state: absent
    autoremove: true
  when:
    - ansible_pkg_mgr == 'dnf'
    - "'kde' not in desktop_env"

- name: Remove KDE if not in use on pacman hosts
  pacman:
    name: plasma
    state: absent
  when:
    - ansible_pkg_mgr == 'pacman'
    - "'kde' not in desktop_env"

- name: Remove MATE if not in use on Ubuntu hosts
  apt:
    name: ubuntu-mate-desktop
    state: absent
    autoremove: true
  when:
    - ansible_pkg_mgr == 'apt'
    - ansible_distribution == 'Ubuntu'
    - "'mate' not in desktop_env"

- name: Remove MATE if not in use on Debian hosts
  apt:
    name: task-mate-desktop
    state: absent
    autoremove: true
  when:
    - ansible_pkg_mgr == 'apt'
    - ansible_distribution == 'Debian'
    - "'mate' not in desktop_env"

- name: Remove MATE if not in use on pacman systems
  pacman:
    name:
      - mate
      - mate-extra
    state: absent
  when:
    - ansible_pkg_mgr == 'pacman'
    - "'mate' not in desktop_env"

- name: Remove XFCE if not in use on apt hosts
  apt:
    name:
      - xfce4
      - xfce4-goodies
    state: absent
    autoremove: true
  when:
    - ansible_pkg_mgr == 'apt'
    - ansible_distribution != 'Debian'
    - "'xfce' not in desktop_env"

- name: Remove XFCE if not in use on Debian hosts
  apt:
    name: task-xfce-desktop
    state: absent
    autoremove: true
  when:
    - ansible_pkg_mgr == 'apt'
    - ansible_distribution == 'Debian'
    - "'xfce' not in desktop_env"

- name: Remove XFCE if not in use on yum hosts
  yum:
    name: xfce4
    state: absent
    autoremove: true
  when:
    - ansible_pkg_mgr == 'yum'
    - "'xfce' not in desktop_env"

- name: Remove XFCE if not in use on dnf hosts
  dnf:
    name: '@Xfce'
    state: absent
    autoremove: true
  when:
    - ansible_pkg_mgr == 'dnf'
    - "'xfce' not in desktop_env"

- name: Remove XFCE if not in use on pacman hosts
  pacman:
    name:
      - xfce4
      - xfce4-goodies
    state: absent
  when:
    - ansible_pkg_mgr == 'pacman'
    - "'xfce' not in desktop_env"
