---
# tasks file for arc.user_creation
- name: Create the administrative user group
  group:
    name: "{{ admin_user }}"
    state: present

- name: Create the administrative user
  user:
    name: "{{ admin_user }}"
    state: present
    shell: '/bin/bash'
    create_home: true
    password: "{{ admin_password | password_hash('sha512') }}
    update_password: always
    home: "/home/{{ admin_user }}"
    groups: "{{ admin_groups }}"
    append: true

- name: Create the .ssh directory
  file:
    path: "/home/{{ admin_user }}/.ssh"
    state: directory
    owner: "{{ admin_user }}"
    group: "{{ admin_user }}"
    directory_mode: '0700'

- name: Ensure authorized_keys file exists for user
  copy:
    src: admin_authorized_keys
    dest: "/home/{{ admin_user }}/.ssh/authorized_keys"
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: '0600'
    force: true
