---
# tasks file for arc.enable_repos
- name: Add keys to yum/dnf systems
  rpm_key:
    key: "{{ item }}"
    state: present
  when: ansible_pkg_mgr == 'yum' or
        ansible_pkg_mgr == 'dnf'
  loop:
    - 'https://packagecloud.io/AtomEditor/atom/gpgkey'
    - 'https://download.sublimetext.com/sublimehq-rpm-pub.gpg'

- name: Enable repos on yum and dnf systems
  yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.desc }}"
    file: "{{ item.file }}"
    baseurl: "{{ item.baseurl }}"
  loop:
    - {name: sublime-text,
       desc: Sublime Text Repo,
       file: sublime-text,
       baseurl: 'https://download.sublimetext.com/rpm/stable/x86_64/'}
    - {name: Atom Editor,
       desc: Atom Repo,
       file: atom,
       baseurl: 'https://packagecloud.io/AtomEditor/atom/el/7/$basearch'}
  when: ansible_pkg_mgr == 'yum' or
        ansible_pkg_mgr == 'dnf'

- name: Enable EPEL repo on yum systems
  yum:
    name: epel-release
    state: latest
    update_cache: true
  when: ansible_pkg_mgr == 'yum'

- name: Enable EPEL repo on dnf systems
  dnf:
    name: epel-release
    state: latest
    update_cache: true
  when: ansible_pkg_mgr == 'dnf'

- name: Enable Copr repos on dnf systems
  command:
    cmd: 'dnf copr enable castor/remmina'
    creates: '/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:castor:remmina.repo'
  when: ansible_pkg_mgr == 'dnf'

- name: Enable repos on pacman systems
  lineinfile:
    path: /etc/pacman.conf
    insertafter: "{{ item.after }}"
    line: "{{ item.line }}"
  loop:
    - {after: '[core]',
       line: 'Include = /etc/pacman.d/mirrorlist'}
    - {after: '[extra]',
       line: 'Include = /etc/pacman.d/mirrorlist'}
    - {after: '[community]',
       line: 'Include = /etc/pacman.d/mirrorlist'}
    - {after: '[multilib]',
       line: 'Include = /etc/pacman.d/mirrorlist'}
    #- {after: '[community-testing]',
    #   line: 'Include = /etc/pacman.d/mirrorlist'}
    #- {after: '[multilib-testing]',
    #   line: 'Include = /etc/pacman.d/mirrorlist'}
  when: ansible_distribution == 'Archlinux'

- name: Ensure pacman cache is up to date
  pacman:
    update_cache: true
  when: ansible_distribution == 'Archlinux'

- name: Add keys for Debian/Ubuntu repos
  apt_key:
    url: "{{ item }}"
    state: present
  when: ansible_pkg_mgr == 'apt'
  loop:
    - 'https://packagecloud.io/AtomEditor/atom/gpgkey'
    - 'https://s3.eu-central-1.amazonaws.com/jetbrains-ppa/0xA6E8698A.pub.asc'
    - 'https://download.sublimetext.com/sublimehq-pub.gpg'

- name: Enable Debian/Ubuntu repos
  apt_repository:
    repo: "{{ item.repo }}"
    state: present
    filename: "{{ item.file }}"
  loop:
    - {repo: 'deb http://jetbrains-ppa.s3-website.eu-central-1.amazonaws.com bionic main',
       file: 'intellij.repo'}
    - {repo: 'deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main',
       file: 'atom.repo'}
    - {repo: 'deb https://download.sublimetext.com/ apt/stable/',
       file: 'sublime.repo'}
  when: ansible_pkg_mgr == 'apt'
