---
# tasks file for arc.ansible_config
- name: Create the group for the ansible service user
  group:
    name: "{{ service_user }}"
    state: present

- name: Create the user for the ansible service
  user:
    name: "{{ service_user }}"
    state: present
    system: true
    shell: /bin/bash
    create_home: true
    home: "/home/{{ service_user }}"
    group: "{{ service_user }}"

- name: Ensure permissions on home directory are correctly set
  file:
    path: "/home/{{ service_user }}"
    mode: '0700'

- name: Create the .ssh directory
  file:
    path: "/home/{{ service_user }}/.ssh"
    state: directory
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    directory_mode: '0700'

- name: Ensure authorized_keys file exists for user
  copy:
    src: ansible_authorized_keys
    dest: "/home/{{ service_user }}/.ssh/authorized_keys"
    owner: "{{ service_user }}"
    group: "{{ service_user }}"
    mode: '0600'
    force: true

- name: Ensure user exists in the sudeors file
  lineinfile:
    path: /etc/sudoers
    create: true
    line: "{{ service_user }} ALL=(ALL) NOPASSWD:ALL"
    validate: /usr/sbin/visudo -cf %s
